
enum MoveDirection{
	MOVE_DIRECTION_ARRIBA,
	MOVE_DIRECTION_ABAJO,
	MOVE_DIRECTION_IZQUIERDA,
	MOVE_DIRECTION_DERECHA,
	MOVE_DIRECTION_NONE
};
enum MoveDirection2 {
	MOVE_DIRECTION_ARRIBA2,
	MOVE_DIRECTION_ABAJO2,
	MOVE_DIRECTION_IZQUIERDA2,
	MOVE_DIRECTION_DERECHA2,
	MOVE_DIRECTION_NONE2
};